### ISSUE TITLE
Interaction with the patacrep Python library

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patagui#142]
How should the client interact with the new core (4.0) ? The client is a C++ application, and the core is a Python application

I see two main possibilities:
* (1) Create a Python interpreter inside the client, using something like [Boost Python](http://www.boost.org/doc/libs/1_55_0/libs/python/doc/index.html). This will allow easy access to the translated parameters, and to the exceptions;
* (2) Use system calls. It will grant less flexibility but more portability;

And another possibility (3) would be to rewrite the app in Python, with PySide or PyQt. This would be lot of works, but give the better flexibility.

Choose two options in the three:
* few work, easy access to Python (1)
* few work, easy compiling and port (2)
* easy compiling and port, easy access to Python (3)

**Comment by LaTruelle** [comment]
Salut,

Je suis toujours en train d'essayer de faire marcher patauge avec patacrep 4. Pour l'instant, pythonqt fonctionne très bien, j'arrive à importer le module, mais là ça bloque, en particulier à cause de la différence de typage entre Python et C++ (j'ai un peu de mal à lire le code Python...)

Quand on initialise l'objet SongbookBuilder (https://github.com/patacrep/patacrep/blob/master/patacrep/build.py), on doit lui donner un raw_songbook et un basename. De quel type d'objets parle-t-on alors ? Je dois juste lui donner le chemin vers le fichier .sb et le nom de sortie ou est-ce plus sophistiqué ?

Merci!

**Comment by Luthaf** [comment]
`songbook_builder` est un dictionaire python, et basename et le chemin vers le ficher de sortie voulu, sans extension.

Des exemples d'utilisation sont dans le script principal : https://github.com/patacrep/patacrep/blob/b35da1325fae01d0c352d7eb65baaef6ab0ae9e4/patacrep/songbook.py#L136, et dans patanet : https://github.com/patacrep/patanet/blob/170a7e99c69521773d39f9b83428584f8a057284/generator/build.py#L66

**Comment by LaTruelle** [comment]
Ça progresse lentement mais surement... J'arrive à lire et écrire des fichiers valides, par contre la structure de données ayant un peu changé, j'ai une question sur les datadirs. patacrep cherche les chants répertoriés de manière automatique et récursive dans un datadir donné, ou il faut un chemin complet (relatif par rapport au datadir) ?

**Comment by Luthaf** [comment]
Je n'ai pas tout à fait compris la question. Si on prend la chanson `/home/foo/bar/songs/my_song.sg`, et que `/home/foo/bar` est un datadir, alors il suffit de passer à patacrep le chemin `my_song.sg`. Les chansons sont cherchées dans le dossier `songs` de tous les datadirs connus.

Les carnets de patadata sont en général de bon points de départ. https://github.com/patacrep/patadata/tree/master/books

**Comment by LaTruelle** [comment]
Je pense que ça répond plus ou moins. Un détail seulement: si on prend la chanson `/home/foo/bar/songs/author/my_song.sg`, il faut mettre dans le songbook le datadir `/home/foo/bar` et la chanson `author/my_song.sg`. Est-ce que mettre uniquement `my_song.sg` fonctionnera ?

**Comment by Luthaf** [comment]
Non, je pense qu'il faudra en effet mettre `author/my_song.sg`. @paternal, tu confirme ?

**Comment by paternal** [comment]
Après test, effectivement, c'est nécessaire. Après, c'est discutable…

**Comment by Luthaf** [comment]
Je préfère ce comportement, ça limite les collisions de noms.

**Comment by LaTruelle** [comment]
Oui je suis d'accord. Je voulais juste vérifier comme je suis en train de réimplémenter pas mal de fonctions dans patagui.

**Comment by LaTruelle** [comment]
Et du coup une autre question, patacrep tolère-t-il un datadir qui n'est pas organisé en `datadir/songs` ? En gros, le répertoire `songs` est obligatoire ou juste optionnel ?

**Comment by paternal** [comment]
- Tous les sous-répertoires sont nécessaires dans le sens où un fichier `chanson.sg` placé à la racine du datadir ne sera pas considéré (seulement `songs/chanson.sg`).
- Tous les sous-répertoires sont optionnels dans le sens où s'ils sont absents d'un datadirs, ils sont ignorés silencieusement.

**Comment by LaTruelle** [comment]
#149 a partiellement résolu ça. Il manque le yaml, il y aura une autre issue/PR si nécessaire.
