### ISSUE TITLE
Hungarian Notation

### ISSUE THREAD

**Issue by LaTruelle** [patacrep/patagui#150]
Est-ce que quelqu'un tient beaucoup à la notation hongroise pour les noms de classes/variables ? Sinon, je fais du refactoring sur une branche, je trouve pas ça hyper lisible...

**Comment by Luthaf** [comment]
Je n'y tiens pas, et je ne suis pas fan non plus. Tu utilise quoi à la place ? Sur mes projets perso j'ajoute un suffixe `_` pour distinguer les variables de classe des variables locales.

**Comment by LaTruelle** [comment]
Je fais juste les noms de classes avec la première lettre en majuscules et les variables en minuscules, indifféremment de leur statut. En C++/Qt je n'ai jamais vu l'intérêt de différencier variables de classe / variable locale, mais je peux avoir tort...

**Comment by LaTruelle** [comment]
OK c'est fait dans une branche sur mon fork: bec01160eee015a175e29164beb1be79dde1ba42.

Du coup, ça devient lié à la pull request #149 indirectement.
